# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_added', models.DateField(default=datetime.datetime(2017, 8, 30, 17, 43, 22, 772020))),
                ('image', models.CharField(blank=True, max_length=400, null=True)),
                ('bio', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
